[package]
name = "varianteq"
version = "0.1.0"
authors = ["Josh Leeb-du Toit <josh.leebdutoit@gmail.com>"]
description = "Equality of Enum Variants Ignoring Fields"
keywords = ["enum", "equality", "partialeq", "macro"]
license = "MIT"
readme = "README.md"

[dependencies]
proc-macro2 = "0.3.1"
quote = "0.5.1"
syn = { version = "0.13.0", features = ["full"] }

[lib]
proc-macro = true

[[test]]
name = "tests"
